# Generated by Django 3.1.5 on 2021-01-11 16:56

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('released', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('metacritic_rating', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='GameStudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('founded', models.IntegerField()),
                ('founder', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Игровые студии',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Пользователи',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('director', models.CharField(max_length=50)),
                ('founder', models.CharField(max_length=50)),
                ('founded', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Издатели',
            },
        ),
        migrations.CreateModel(
            name='PersonRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.game')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.person')),
            ],
            options={
                'verbose_name_plural': 'Оценки пользователей',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='rated_games',
            field=models.ManyToManyField(through='main.PersonRating', to='main.Game'),
        ),
        migrations.CreateModel(
            name='GameGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.game')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.genre')),
            ],
            options={
                'verbose_name_plural': 'Жанры для игр',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='game_studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.gamestudio'),
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(through='main.GameGenre', to='main.Genre'),
        ),
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.publisher'),
        ),
    ]
