# Generated by Django 3.1.5 on 2021-01-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210111_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='games',
            field=models.ManyToManyField(through='main.GameGenre', to='main.Game'),
        ),
    ]
