# Generated by Django 3.1.5 on 2021-01-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_genre_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='gamestudio',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name='gamegenre',
            constraint=models.UniqueConstraint(fields=('game', 'genre'), name='unique_game_genre'),
        ),
        migrations.AddConstraint(
            model_name='personrating',
            constraint=models.UniqueConstraint(fields=('person', 'game'), name='unique_game_person_rating'),
        ),
    ]
